DROP TABLE IF EXISTS DOCUMENT;
CREATE TABLE DOCUMENT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	file_path TEXT NOT NULL,
	url TEXT NOT NULL,
	language_code TEXT NOT NULL DEFAULT 'en',
	is_generated INTEGER NOT NULL DEFAULT 1,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS DOCUMENT_TEXT;
CREATE TABLE DOCUMENT_TEXT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	file_path TEXT NOT NULL,
	text_data TEXT,
	start_time REAL,
	duration REAL
);

DROP TABLE IF EXISTS DOCUMENT_FULL_TEXT;
CREATE TABLE DOCUMENT_FULL_TEXT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	file_path TEXT NOT NULL,
	language TEXT NOT NULL,
	data TEXT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS CHAT_RESPONSE;
CREATE TABLE CHAT_RESPONSE(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	model TEXT NOT NULL,
	message_role TEXT,
	message_content TEXT,
	done_reason TEXT,
	done INTEGER,
	total_duration INTEGER,
	load_duration INTEGER,
	prompt_eval_count INTEGER,
	prompt_eval_duration INTEGER,
	eval_count INTEGER,
	eval_duration INTEGER,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS CHAT_REQUEST;
CREATE TABLE CHAT_REQUEST(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	model TEXT NOT NULL,
	message_role TEXT,
	message_content TEXT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
